server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
dubbo:
  application:
    name: shop_back
  consumer:
    check: false
    timeout: 10000
    retries: 0
  registry:
    address: zookeeper://192.168.79.188:2181
upload:
  path: D:/demo/

fdfs:
  connect-timeout: 10000
  so-timeout: 10000
  tracker-list: 192.168.79.188:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false